//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulLenchenkoP2Var2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaiTable
    {
        public int Id { get; set; }
        public string Owner_Name { get; set; }
        public string Car_Brand { get; set; }
        public string Car_Number { get; set; }
        public string Colour { get; set; }
        public System.DateTime Yaer_of_Manufacture { get; set; }
    }
}
